[package]
name = "whatfeatures"
version = "0.4.2"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

build = "build.rs"

[dependencies]
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
attohttpc = { version = "0.4.1", features = ["json"] }
gumdrop = "0.6.0"
yansi = "0.5.0"
