[package]
name = "whatfeatures"
version = "0.2.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
attohttpc = { version = "0.4.1", features = ["json"] }
gumdrop = "0.5.0"
yansi = "0.5.0"
