[package]
edition = "2018"
name = "whatfeatures"
version = "0.5.6"
authors = ["museun <museun@outlook.com>"]
repository = "https://github.com/museun/whatfeatures"
description = "display features, versions and dependencies of crates"
keywords = [ "features", "dependencies", "crates", "cargo" ]
license = "0BSD"
readme = "README.md"
build = "build.rs"
autobins = false

[[bin]]
name = "cargo-whatfeatures"
path = "src/bin/main.rs"

[dependencies]
log = "0.4.8"
thiserror = "1.0.9"
yansi = "0.5.0"
structopt = { version = "0.3.5", default-features = false }
lexical_bool = "0.1.3"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.44"
attohttpc = { version = "0.6.0", features = ["json"] }

