[package]
edition = "2018"
name = "whatfeatures"
version = "0.5.1"
authors = ["museun <museun@outlook.com>"]
repository = "https://github.com/museun/whatfeatures"
description = "display features, versions and dependencies of crates"
keywords = [ "features", "dependencies", "crates" ]
license = "0BSD"
readme = "README.md"
build = "build.rs"
autobins = false

[[bin]]
name = "whatfeatures"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
attohttpc = { version = "0.4.1", features = ["json"] }
gumdrop = "0.6.0"
yansi = "0.5.0"
lexical_bool = "0.1.2"
log = "0.4.7"
